config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :users
  devise_for :doctors

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :users do
    resources :cases
  end

  resources :doctors do
    resources :cases
  end

  resources :categories

  get 'doctors/category/:category_id', to: 'doctors#index', as: 'doctors_by_category'
  get 'landing', to: 'pages#landing_page', as: 'landing'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      if user.admin?
        can :read, ActiveAdmin::Page, :name => "Dashboard"
        can :manage, :all
      else
        can :manage, Case
        can :manage, User
        can :read, Doctor
      end
    end
    can :manage, Doctor
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable, authentication_keys: [:email]

  def admin?
    true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/case.rb
class Case < ApplicationRecord
  belongs_to :doctor, validate: true
  belongs_to :user

  validate :validate_cases

  def validate_cases
    errors.add(:case, 'Too much open cases for a doctor') if doctor.cases.where(status: true).count > 10
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :doctors

  validates :name, uniqueness: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :category, optional: true
  has_many :users, through: :cases
  has_many :cases, dependent: :destroy
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:phone_number]

  validates :phone_number, format: { with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/ },
                           uniqueness: true

  def fullname
    "#{name} #{surname}"  
  end
  
  def email_required?
    false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:phone_number]
  has_many :doctors, through: :cases
  has_many :cases, dependent: :destroy
  has_one_attached :avatar

  validates :phone_number, format: { with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/ }

  def email_required?
    false
  end

  def fullname
    "#{name} #{surname}"  
  end

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protect_from_forgery

  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end

  protected
  
  def configure_permitted_parameters
    added_attrs = [:name, :surname, :phone_number, :avatar, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController

  def index
    if params[:doctor_id]
      @cases = Case.where(doctor_id: params[:doctor_id])
    elsif params[:user_id]
      @cases = Case.where(user_id: params[:user_id])
    end
  end

  def edit
    set_doctor
    set_case
  end

  def new
    set_user
    @case = @user.cases.build
    @doctors = Doctor.all.collect {|doctor| [doctor.fullname, doctor.id]}
  end

  def create
    set_user
    @case = @user.cases.build(required_params)

    if @case.save
      flash[:notice] = "Successfully created."
      redirect_to user_cases_path(@user)
    else
      flash[:notice] = @case.errors.full_messages.to_sentence
      redirect_to new_user_case_path
    end
  end

  def update
    set_doctor
    set_case
    if @case.update(required_params)
      flash[:notice] = "Successfully updated."
      redirect_to doctor_cases_path(@doctor)
    else
      flash[:notice] = @case.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end

  def set_case
    @case = Case.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def required_params
    params.require(:case).permit(:question, :status, :doctor_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = Category.all
    if params[:category_id]
      @doctors = Doctor.where(category_id: params[:category_id])
    else
      @doctors = Doctor.all
    end
  end

  def show
    set_doctor
  end

  def patients
    set_doctor
    @patients = @doctor.cases
  end

  def edit
    set_doctor
  end

  def update
    set_doctor
    if @doctor.update(required_params)
      flash[:notice] = "Successfully updated."
      redirect_to @doctor
    else
      flash[:error] = @doctor.errors.full_messages.to_sentence
      render :edit
    end
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def required_params
    params.require(:doctor).permit(:email, :phone_number, :avatar, :name, :surname)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing_page
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    set_user
  end

  def update
    set_user
    @user.update(required_params)

    redirect_to @user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def required_params
    params.require(:user).permit(:email, :phone_number, :avatar, :name, :surname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_doctor?
    current_doctor.present?
  end

  def destroy_session_link
    is_doctor? ? destroy_doctor_session_path : destroy_user_session_path
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/cases/edit.html.erb
<%= form_for [@doctor, @case] do |f| %>
  <div class="mb-3">
    <%= f.label :answer, class: 'form-label' %>
    <%= f.text_area :answer, class: 'form-control' %>
  </div>
  <%= f.hidden_field :status, value: false %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/cases/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'New question', new_user_case_path(current_user.id) %>
<% end %>

<% if @cases.count > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Status</th>
        <th scope="col">Avatar</th>
        <th scope="col">Full name</th>
        <th scope="col">Phone</th>
        <th scope="col">Email</th>
        <th scope="col">Question</th>
        <th scope="col">Answer</th>
        <% if doctor_signed_in? %>
          <th scope="col">Reply</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
        <% @cases.each do |c| %>
          <tr>
            <td><%= c.id %></td>
            <td><%= c.status ? 'Open' : 'Closed' %></td>
            <td>
              <% if c.user.avatar.attached? %>
                <%= cl_image_tag(c.user.avatar.key, height: 100, crop: :scale, :radius => 25) %>
              <% end %>
            </td>
            <td><%= c.user.fullname %></td>
            <td><%= c.user.phone_number %> </td>
            <td><%= c.user.email %> </td>
            <td><%= c.question %> </td>
            <td><%= c.answer %> </td>
            <% if doctor_signed_in? %>
              <td><%= link_to 'Answer', edit_doctor_case_path(c.doctor.id, c.id), class: 'btn btn-primary' %> </td>
            <% end %>
          </tr>
        <% end %>
    </tbody>
  </table>
<% else %>
  <% if user_signed_in? %>
    <p>No questions</p>
  <% elsif doctor_signed_in? %>
    <p>No open cases</p>
  <% end %>
<% end %>


app/views/cases/new.html.erb
<%= form_for [@user, @case] do |f| %>
  <div class="mb-3">
    <%= f.label :question, class: 'form-label' %>
    <%= f.text_area :question, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :doctor_id, class: 'form-label' %>
    <%= f.select(:doctor_id, options_for_select(@doctors), {}, { :class => 'form-select' }) %>
  </div>
  <%= f.hidden_field :status, value: true %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/doctors/edit.html.erb
<%= form_for @doctor do |f| %>
  <div class="mb-3">
    <%= f.label :avatar, class: 'form-label' %>
    <%= f.file_field :avatar, class: 'form-control', direct_upload: true %>
  </div>

  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :surname, class: 'form-label' %>
    <%= f.text_field :surname, class: 'form-control' %>
  </div>
  
  <div class="mb-3">
    <%= f.label :email, class: 'form-label' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :phone_number, class: 'form-label' %>
    <%= f.phone_field :phone_number, class: 'form-control', id: 'phone_field' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/doctors/index.html.erb
Sort by: <%= link_to 'All', doctors_path, class: 'link-primary' %> | 
<% @categories.each do |category| %>
  <%= link_to category.name, doctors_by_category_path(category.id), class: 'link-primary' %> | 
<% end %>
<br/>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Avatar</th>
      <th scope="col">Full name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col">Category</th>
    </tr>
  </thead>
  <tbody>
      <% @doctors.each do |doctor| %>
        <tr>
          <td><%= doctor.id %></td>
          <td>
            <% if doctor.avatar.attached? %>
              <%= cl_image_tag(doctor.avatar.key, height: 100, crop: :scale, :radius => 25) %>
            <% end %>
          </td>
          <td><%= doctor.fullname %></td>
          <td><%= doctor.phone_number %> </td>
          <td><%= doctor.email  %> </td>
          <td><%= doctor.category ? doctor.category.name : 'None' %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/doctors/show.html.erb
<div class="card" style="width: 400px;">
  <% if @doctor.avatar.attached? %>
    <%= cl_image_tag(@doctor.avatar.key, width: 400, crop: :scale) %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= @doctor.fullname %></h5>
    <p class="card-text"><%= @doctor.phone_number %></p>
    <p class="card-text"><%= @doctor.email %></p>
    <%= link_to 'Change profile', edit_doctor_path(@doctor), class: 'btn btn-primary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polyclinic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Polyclinic</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
              </li>

              <% if user_signed_in? || doctor_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Profile', current_user ? user_path(current_user.id) : doctor_path(current_doctor.id), class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Landing page', landing_path, class: 'nav-link' %>
                </li>
              <% end %>
              
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Doctors list', doctors_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'My questions', user_cases_path(current_user), class: 'nav-link' %>
                </li>
              <% elsif doctor_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Patients list', doctor_cases_path(current_doctor), class: 'nav-link' %>
                </li>
              <% end %>

              <li class="nav-item d-flex">
                <% if user_signed_in? || doctor_signed_in? %>
                  <%= link_to 'Sign out', destroy_session_link, class: 'nav-link', data: {turbo_method: :delete} %>
                <% else %>
                  <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <% if notice %>
        <div class="alert alert-warning" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/landing_page.html.erb
<h2>Landing</h2>
<hr>
<h5>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat est deleniti eligendi reiciendis ab maxime a nemo, ex tenetur animi, culpa accusamus possimus quo similique, libero quibusdam mollitia voluptatibus! Aspernatur!</h5>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique doloremque quas quae consequuntur rerum dolorum ad asperiores amet voluptates mollitia, sit, a facilis fugiat dolorem totam nostrum reiciendis harum ipsa? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero ducimus reiciendis consequatur nostrum obcaecati libero sint asperiores, debitis totam magni, est atque possimus nemo eveniet id dolorum, ipsa cupiditate. Incidunt!</p>
<hr>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <div class="mb-3">
    <%= f.label :avatar, class: 'form-label' %>
    <%= f.file_field :avatar, class: 'form-control', direct_upload: true %>
  </div>

  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :surname, class: 'form-label' %>
    <%= f.text_field :surname, class: 'form-control' %>
  </div>
  
  <div class="mb-3">
    <%= f.label :email, class: 'form-label' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :phone_number, class: 'form-label' %>
    <%= f.phone_field :phone_number, class: 'form-control' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.phone_number %><br/>
  <%= user.email %><br/>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Avatar</th>
      <th scope="col">Full name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td>
            <% if user.avatar.attached? %>
              <%= cl_image_tag(user.avatar.key, height: 200, crop: :scale) %>
            <% end %>
          </td>
          <td><%= user.fullname %></td>
          <td><%= user.phone_number %> </td>
          <td><%= user.email  %> </td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="card" style="width: 400px;">
  <% if @user.avatar.attached? %>
    <%= cl_image_tag(@user.avatar.key, width: 400, crop: :scale) %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= @user.fullname %></h5>
    <p class="card-text"><%= @user.phone_number %></p>
    <p class="card-text"><%= @user.email %></p>
    <%= link_to 'Change profile', edit_user_path(@user), class: 'btn btn-primary' %>
  </div>
</div>